FROM python:3.11-slim
WORKDIR /app

COPY requirements.dev.txt /app/requirements.dev.txt
RUN pip install --no-cache-dir -r requirements.dev.txt

# Code wird im Dev per Volume gemountet
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
